[project]
name = "qc-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.4",
    "numpy>=2.3.1",
    "onnxruntime-qnn>=1.22.0",
    "streamlit>=1.46.1",
    "tokenizers>=0.21.2",
]
